name: alazkar
description: A new Flutter project.

publish_to: "none"

version: 0.1.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_colorpicker: ^1.0.3
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.2.2
  get_storage: ^2.1.1
  material_design_icons_flutter: ^7.0.7296
  path: ^1.8.3
  path_provider: ^2.1.0
  share_plus: ^7.1.0
  sqflite: ^2.3.0
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  lint: ^2.1.2

flutter:
  uses-material-design: true

  assets:
    - assets/db/
    - assets/sounds/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Uthmanic
      fonts:
        - asset: assets/fonts/uthmanic_hafs_ver12.otf
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
    - family: Kitab
      fonts:
        - asset: assets/fonts/kitab.ttf
